/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.brightsparklabs.filestore

import spock.lang.Specification

/**
 * Unit tests for {@link Filestore}.
 */
class FilestoreTest extends Specification {
}
